const jwt = require('jsonwebtoken');

/**
 * supportAuthGuard — Super Admin Support Access Impersonation Helper
 * 
 * Inspects incoming Authorization header for Support Access JWT tokens
 * generated by Super Admin Control Plane.
 * 
 * @param {Object} req - Express request object
 * @returns {Object|null} Decoded support access payload if valid, or null
 */
function extractSupportAccessUser(req) {
    const authHeader = req.headers['authorization'];
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
        return null;
    }

    const token = authHeader.split(' ')[1];
    const secret = process.env.PRODUCT_SECRET || process.env.BOOTSTRAP_SECRET;

    if (!secret) return null;

    try {
        const decoded = jwt.verify(token, secret);
        if (decoded.type === 'SUPPORT' && decoded.impersonating === true) {
            return {
                id: decoded.id || 'admin_support',
                name: decoded.name || 'Super Admin',
                email: decoded.email || 'support@s3softs.com',
                role: 'Developer', // High privilege developer role for support debugging
                tenantId: decoded.tenantId,
                shopId: decoded.tenantId,
                isImpersonating: true
            };
        }
    } catch (_) {
        // Token was not signed with PRODUCT_SECRET or is expired — ignore and fallback to regular user auth
    }

    return null;
}

module.exports = {
    extractSupportAccessUser
};
